title: IGOVES.GITHUB.IO
author: Igor Veselov
email: igoves.dev@gmail.com
url: https://igoves.github.io
baseurl: "/"
description: > 
  Software and services for e-commerce

permalink: /:slug

favicon: "logo.svg"

remote_theme: riggraz/no-style-please 

theme_config:
  appearance: "auto" 
  back_home_text: "< back"
  date_format: "%Y-%m-%d" 
  show_description: true 

sass:
  style: :compressed

plugins:
  - jekyll-seo-tag
  - jekyll-target-blank
  - jekyll-tagging-related_posts

target-blank:
    rel: nofollow