title: IGOVES
author: Igor Veselov
email: igoves.dev@gmail.com
url: https://igoves.github.io
baseurl: "/"
description: > 
  Software and services for e-commerce

favicon: "favicon.ico"
remote_theme: riggraz/no-style-please 

permalink: /:slug

theme_config:
  back_home_text: "< to home"
  date_format: "%Y-%m-%d" 
  show_description: true 

sass:
  style: :compressed

plugins:
  - jekyll-seo-tag
  - jekyll-target-blank
  - jekyll-feed

target-blank:
    rel: nofollow

