title: IGOVES
author: Igor Veselov
email: igoves.dev@gmail.com
url: https://igoves.github.io
baseurl: "/"
description: > 
  Software and services for e-commerce



favicon: "favicon.ico"

remote_theme: riggraz/no-style-please 

theme_config:
  back_home_text: "< to home"
  date_format: "%Y-%m-%d" 
  show_description: true 

sass:
  style: :compressed

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-target-blank
  - jekyll-archives
  - jekyll-feed

target-blank:
    rel: nofollow
    
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: /categories/:slug
    tag: /tags/:slug
    
    
compress_html:
  clippings: all
  ignore:
    envs: development
    
    
permalink: /:slug
paginate_path: /page:num
paginate: 5